services:
  - type: web
    name: stocktracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
    plan: free
    healthCheckPath: /api/health